name: Deploy para VPS
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Escrever chave privada
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Garantir destino existe
        run: |
          ssh -i id_rsa -p 22 -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST }} \
            "mkdir -p /home/sac.com/public_html"

      - name: Rsync (absoluto, sem truques)
        run: |
          rsync -rltgoDzvO --delete \
            -e "ssh -i id_rsa -p 22 -o StrictHostKeyChecking=no" \
            ./ root@${{ secrets.REMOTE_HOST }}:/home/sac.com/public_html/

      
