name: Deploy para VPS
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # (Opcional, mas recomendado) Garanta que o diretório existe
      - name: Garantir destino existe
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root                     # idealmente, use o usuário do site no CyberPanel
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /home/sac.com/public_html

      - name: Rsync deploy
        uses: easingthemes/ssh-deploy@main
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-host: ${{ secrets.REMOTE_HOST }}
          remote-user: root                  # troque para o dono do site se tiver
          remote-port: 22
          source: "."
          target: "/home/sac.com/public_html/"
          args: "-rltgoDzvO --delete"
